### ISSUE TITLE
검색 후 엔터를 누르니 반응이 없습니다

### ISSUE THREAD

**Issue by r2verse** [sungminoh/alfred-workflow-stockprice#2]
하이시에라 10.13.2 사용사입니다

**Comment by sungminoh** [comment]
I released a fixed version. Please try [this](https://github.com/sungminoh/alfred-workflow-stockprice/releases/download/3.0.3/stockprice_checker_v3.0.2.alfredworkflow).

**Comment by r2verse** [comment]
오홋~ 잘되네요 ㅎㅎ
감사합니다!!!
