### ISSUE TITLE
안녕하세요. 현재는 이용하기 어려울까요?

### ISSUE THREAD

**Issue by jongsinyang** [sungminoh/alfred-workflow-stockprice#3]
안녕하세요. 현재는 이용하기 어려울까요?
빅서 사용 중입니다.

확인 부탁 드립니다 ―ㅜ

**Comment by sungminoh** [comment]
이슈 오픈해주신 덕분에 오랫만에 확인했네요.
고쳐두었습니다. ([다운로드](https://github.com/sungminoh/alfred-workflow-stockprice/releases/download/3.0.6/Naver.finance.alfredworkflow))
확인해보시고 알려주세요. 안되면 reopen 부탁드립니다.

**Comment by jongsinyang** [comment]
확인하였습니다. 감사합니다!!
